#---------------------------------------------------------------------
# Tools
#---------------------------------------------------------------------
[tools]
python = "3.14"
uv = "0.12.19"

#---------------------------------------------------------------------
# Environment variables
#---------------------------------------------------------------------
[env]
ES_VERSION = "9.5.4"
LOGSTASH_VERSION = "9.5.4"
KIBANA_VERSION = "9.5.4"

#---------------------------------------------------------------------
# Tasks
#---------------------------------------------------------------------

# - Stack management -
[tasks.setup]
description = "Set up virtual environment"
run = "uv sync"

[tasks.start]
description = "Start stack"
run = "docker compose up -d"

[tasks.stop]
description = "Stop stack"
run = "docker compose stop"

[tasks.clean]
description = "Clean all stack resources (services, volumes, networks)"
run = "docker compose down --volumes --remove-orphans"

[tasks.reset]
description = "Reset stack from scratch"
run = [
    { task = "clean" },
    { task = "start" }
]

[tasks.logs]
description = "Get logs from a given service"
usage = '''
arg "<service>" help="Name of the service to display logs from" {
  choices "es-init" "es01" "es02" "es03" "logstash" "kibana"
}
flag "-f --follow" help="Follow log output" default=#false
'''
run = "docker compose logs {{ usage.service }} {% if usage.follow %}--follow{% endif %}"

# - Cluster management -
[tasks.status]
description = "Get cluster status"
quiet = true
run = "curl -s -XGET http://localhost:9200/_cluster/health?pretty=true"

[tasks.health]
description = "Retrieve cluster health status report"
quiet = true
run = "curl -s -XGET http://localhost:9200/_health_report?pretty=true"

# - Datasets management -
[tasks.load-dataset]
description = "Load dataset into an ElasticSearch index"
raw_args = true
run = "uv run scripts/load_dataset.py"

# - Licensing -
[tasks."license:start-trial"]
description = "Start a 30-day trial, which gives access to all subscription features"
quiet = true
run = "curl -s -XPOST http://localhost:9200/_license/start_trial?acknowledge=true"

[tasks."license:info"]
description = "Get license information"
quiet = true
run = "curl -s -XGET http://localhost:9200/_license?pretty=true"

# - Misc -
[tasks.kibana]
description = "Open Kibana console in browser"
run = "xdg-open http://localhost:5601"

#---------------------------------------------------------------------
# Settings
#---------------------------------------------------------------------
[settings]
python.uv_venv_auto = "create|source"