#---------------------------------------------------------------------
# Tools
#---------------------------------------------------------------------
[tools]
python = "3.14"
uv = "0.12.3"

#---------------------------------------------------------------------
# Environment variables
#---------------------------------------------------------------------
[env]
ES_VERSION = "9.5.1"
KIBANA_VERSION = "9.5.1"

#---------------------------------------------------------------------
# Tasks
#---------------------------------------------------------------------

# - Stack management -
[tasks.setup]
description = "Set up virtual environment"
run = "uv sync"

[tasks.start]
description = "Start stack"
run = "docker compose up -d"

[tasks.stop]
description = "Stop stack"
run = "docker compose stop"

[tasks.clean]
description = "Clean all stack resources (services, volumes, networks)"
run = "docker compose down --volumes --remove-orphans"

[tasks.reset]
description = "Reset stack from scratch"
run = [
    { task = "clean" },
    { task = "start" }
]

# - Service management -
[tasks.logs]
description = "Get logs from a given service"
usage = '''
arg "<service>" help="Name of the service to display logs from" {
  choices "es-init" "es01" "es02" "es03" "kibana"
}
flag "-f --follow" help="Follow log output" default=#false
'''
run = "docker compose logs {{ usage.service }} {% if usage.follow %}--follow{% endif %}"

# - Cluster management -
[tasks."cluster:health"]
description = "Retrieve cluster health report"
usage = '''
flag "-v --verbose" help="Display more information about the health of the system" default=#false
'''
run = "curl -s -XGET 'http://localhost:9200/_health_report?format=yaml&verbose={{ usage.verbose }}'"

# - Licensing -
[tasks."license:start-trial"]
description = "Start a 30-day trial, which gives access to all subscription features"
run = "curl -s -XPOST 'http://localhost:9200/_license/start_trial?acknowledge=true&format=yaml'"

[tasks."license:info"]
description = "Get license information"
run = "curl -s -XGET 'http://localhost:9200/_license?format=yaml'"

# - Misc -
[tasks.kibana]
description = "Open Kibana console in browser"
run = "xdg-open http://localhost:5601"

[tasks.load-dataset]
description = "Load dataset data into an ElasticSearch index"
usage = '''
arg "<file>" help="Path to dataset file"
flag "-i --index <name>" help="Name of the index"
flag "-s --settings_file <file>" help="Path to index settings file"
'''
run = '''
uv run scripts/load_dataset.py \
  {{ usage.file }} \
  {% if usage.index %}--index={{ usage.index }}{% endif %} \
  {% if usage.settings_file %}--settings-file={{ usage.settings_file }}{% endif %} \
  --chunk-size=10000
'''


#---------------------------------------------------------------------
# Settings
#---------------------------------------------------------------------
[settings]
python.uv_venv_auto = "create|source"